-- Script SQL para crear las tablas en Oracle Database
-- Gestión de Laboratorios y Resultados de Análisis

-- ============================================
-- TABLA USUARIOS
-- ============================================
CREATE TABLE USUARIOS (
    ID NUMBER(19) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    ROL VARCHAR2(20) NOT NULL CHECK (ROL IN ('ADMINISTRADOR', 'PACIENTE', 'TECNICO_LABORATORIO')),
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP
);

CREATE SEQUENCE USUARIOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TRIGGER USUARIOS_ID_TRG
    BEFORE INSERT ON USUARIOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := USUARIOS_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_ROL ON USUARIOS(ROL);

-- ============================================
-- TABLA LABORATORIOS
-- ============================================
CREATE TABLE LABORATORIOS (
    ID NUMBER(19) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(200) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP
);

CREATE SEQUENCE LABORATORIOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TRIGGER LABORATORIOS_ID_TRG
    BEFORE INSERT ON LABORATORIOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := LABORATORIOS_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_LABORATORIOS_TIPO ON LABORATORIOS(TIPO);
CREATE INDEX IDX_LABORATORIOS_ACTIVO ON LABORATORIOS(ACTIVO);

-- ============================================
-- TABLA RESULTADOS
-- ============================================
CREATE TABLE RESULTADOS (
    ID NUMBER(19) PRIMARY KEY,
    PACIENTE_ID NUMBER(19) NOT NULL,
    LABORATORIO_ID NUMBER(19) NOT NULL,
    TIPO_ANALISIS VARCHAR2(100) NOT NULL,
    RESULTADO CLOB NOT NULL,
    OBSERVACIONES CLOB,
    FECHA_ANALISIS TIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP
);

CREATE SEQUENCE RESULTADOS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TRIGGER RESULTADOS_ID_TRG
    BEFORE INSERT ON RESULTADOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := RESULTADOS_SEQ.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_RESULTADOS_PACIENTE ON RESULTADOS(PACIENTE_ID);
CREATE INDEX IDX_RESULTADOS_LABORATORIO ON RESULTADOS(LABORATORIO_ID);
CREATE INDEX IDX_RESULTADOS_FECHA ON RESULTADOS(FECHA_ANALISIS);

-- ============================================
-- DATOS INICIALES - 3 LABORATORIOS
-- ============================================
INSERT INTO LABORATORIOS (NOMBRE, DIRECCION, TELEFONO, TIPO, ACTIVO)
VALUES ('Laboratorio Clínico Central', 'Av. Principal 123, Santiago', '+56 2 2345 6789', 'Análisis Clínicos', 1);

INSERT INTO LABORATORIOS (NOMBRE, DIRECCION, TELEFONO, TIPO, ACTIVO)
VALUES ('Laboratorio de Análisis Especializados', 'Calle Especializada 456, Valparaíso', '+56 32 1234 5678', 'Análisis Especializados', 1);

INSERT INTO LABORATORIOS (NOMBRE, DIRECCION, TELEFONO, TIPO, ACTIVO)
VALUES ('Laboratorio de Patología', 'Boulevard Médico 789, Concepción', '+56 41 9876 5432', 'Patología', 1);

-- ============================================
-- USUARIOS DE PRUEBA
-- ============================================
-- Nota: Las contraseñas deben ser hasheadas con BCrypt
-- Contraseña de ejemplo: "Admin123!" (debe ser hasheada)
-- Para pruebas, usar el endpoint de registro

COMMIT;

-- Verificar datos
SELECT * FROM LABORATORIOS;
SELECT COUNT(*) AS TOTAL_LABORATORIOS FROM LABORATORIOS;

